"""Pydantic models for structured LLM responses using Instructor."""

from pydantic import BaseModel, Field
from typing import List, Optional, Literal


class ArtifactModel(BaseModel):
    """Model for a single artifact generated by the LLM."""

    type: Literal["code", "html", "table", "json", "mermaid"] = Field(
        ...,
        description="Type of artifact: code, html, table, json, or mermaid"
    )
    language: Optional[str] = Field(
        None,
        description="Programming language for code artifacts (e.g., python, javascript). Only for type='code'."
    )
    title: str = Field(
        ...,
        description="Descriptive title for the artifact"
    )
    content: str = Field(
        ...,
        description="The actual content of the artifact (code, HTML, table data, JSON, or mermaid diagram syntax)"
    )


class StructuredLLMResponse(BaseModel):
    """Structured response from LLM with optional artifacts.

    The LLM must return this exact structure:
    - text: The main explanation/answer
    - artifacts: Optional list of code, diagrams, tables, etc. to display separately
    """

    text: str = Field(
        ...,
        description="Main text response explaining the answer. This is what appears in the chat."
    )
    artifacts: List[ArtifactModel] = Field(
        default_factory=list,
        description="Optional list of artifacts (code examples, diagrams, tables) to display in the artifact panel"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "text": "Here's a Python function to calculate fibonacci numbers. See the code artifact for the implementation.",
                "artifacts": [
                    {
                        "type": "code",
                        "language": "python",
                        "title": "Fibonacci Function",
                        "content": "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n-1) + fibonacci(n-2)"
                    }
                ]
            }
        }
